### ISSUE TITLE
correct way to start a detached process

### ISSUE THREAD

**Issue by jonschull** [tomerfiliba/plumbum#382] opened 2018-03-18 19:13 UTC
Plumbum is great.  But I guess I don't understand how to run a background service.

My program runs a server before it manages a client.
from the commandline, I would type 
> python  path-to-dev_appserver.py   path-to-app.yaml  

with plumbum, I do...

python = local['python']
python( path-to-dev_appserver.py,  path-to-app.yaml ) &NOHUP &BG
print(' I never get here!')

My command does run the server, but I never get to the next line ...

**Comment by ASMfreaK** [comment] 2018-03-18 20:26
If I understand your intent correctly - you should use something like this:
```python
python = local['python']
python['path-to-dev_appserver.py', 'path-to-app.yaml'] & NOHUP(stdout='/dev/null')
```

**Comment by ASMfreaK** [comment] 2018-03-18 21:45
If the problem is solved, please, close the issue.

**Closed** 2018-03-19 20:49 UTC
