### ISSUE TITLE
EOFError connecting to RHEL5 / RHEL6 remotes

### ISSUE THREAD

**Issue by eripa** [tomerfiliba/plumbum#111] opened 2014-02-21 07:27 UTC
I'm currently experiencing issues setting up remotes towards RHEL5 & 6 remotes. I'm getting a stack trace with EOFError (see below). plumbum version 1.4.0. Python 3.2.3 & 3.3.4

Connecting to remote Mac OS X 10.9.1 and Ubuntu 12.04.4 LTS works fine.

    debug1: Local version string SSH-2.0-OpenSSH_6.5

#### RHEL 5 OpenSSH ####
    debug1: Remote protocol version 2.0, remote software version OpenSSH_4.3
    debug1: match: OpenSSH_4.3 pat OpenSSH_4* compat 0x00000000

#### RHEL 6 OpenSSH ####
    debug1: Remote protocol version 2.0, remote software version OpenSSH_5.3
    debug1: match: OpenSSH_5.3 pat OpenSSH_5* compat 0x0c000000

#### OS X 10.9.1 OpenSSH ####
    debug1: Remote protocol version 2.0, remote software version OpenSSH_6.2
    debug1: match: OpenSSH_6.2 pat OpenSSH* compat 0x04000000

#### Ubuntu 12.04 OpenSSH ####
    debug1: Remote protocol version 2.0, remote software version OpenSSH_5.9p1 Debian-5ubuntu1.1
    debug1: match: OpenSSH_5.9p1 Debian-5ubuntu1.1 pat OpenSSH_5* compat 0x0c000000

### Traceback ###

    Traceback (most recent call last):
      File "./plum-e.py", line 15, in <module>
        with SshMachine(ssh_host, user=ssh_user, ssh_command=ssh, scp_command=scp, keyfile=ssh_key_path) as remote:
      File "/usr/lib/python3.2/site-packages/plumbum/machines/ssh_machine.py", line 101, in __init__
        BaseRemoteMachine.__init__(self, encoding = encoding, connect_timeout = connect_timeout)
      File "/usr/lib/python3.2/site-packages/plumbum/machines/remote.py", line 124, in __init__
        self._session = self.session()
      File "/usr/lib/python3.2/site-packages/plumbum/machines/ssh_machine.py", line 145, in session
        self.encoding, isatty, self.connect_timeout)
      File "/usr/lib/python3.2/site-packages/plumbum/machines/session.py", line 141, in __init__
        self.run("")
      File "/usr/lib/python3.2/site-packages/plumbum/machines/session.py", line 224, in run
        return run_proc(self.popen(cmd), retcode)
      File "/usr/lib/python3.2/site-packages/plumbum/commands/processes.py", line 186, in run_proc
        stdout, stderr = proc.communicate()
      File "/usr/lib/python3.2/site-packages/plumbum/machines/session.py", line 92, in communicate
        line = pipe.readline()
      File "/usr/lib/python3.2/site-packages/plumbum/machines/session.py", line 42, in readline
        raise EOFError()
    EOFError

**Comment by magixx** [comment] 2015-07-15 14:18
Been having the same issue on Solaris 10 SPARC, the default shell on the system is set to bash. I've not noticed this issue with Solaris 11 X86. Other variations untested so far.

**Comment by henryiii** [comment] 2015-07-15 20:30
Does this happen with the latest plumbum? I can connect to CentOS 5.
By the way, you can use IPython and it's `%debug` magic to check the values of the variables.

**Comment by henryiii** [comment] 2015-07-18 20:25
Fun fact: if you can't connect because the remote does not exist, this is exactly the error you get. Try to connect to a non-existing server and you'll see this same error message.

**Comment by rayrapetyan** [comment] 2015-07-19 13:24
Actually after changing the default shell on the REMOTE machine to "bash" everything works well. In comment above I've misinterpreted recommendations and changed the shell on the host machine, not the remote one. Still, what's so special with tcsh that it doesn't work?

**Comment by henryiii** [comment] 2015-07-22 01:31
The problem is that tsch cannot redirect output, so the commands:
```bash
printenv "HOSTNAME" ;
echo ;
echo $? ; 
echo \'--.END664027832.1558471.--\' ;
echo \'--.END664027832.1558471.--\' 1 > & 2'
```
fails to write the marker to the stderr when the remote machine is tcsh. So, plumbum doesn't see the marker and acts like the machine isn't there. There might not be a fix, except changing the shell on the remote machine, but I'm hoping for better error messages for this case, and the no host found case. If no one finds a solution by the time I finish my color addition, I'll see what I can do.

**Comment by henryiii** [comment] 2015-09-18 14:20
Plumbum's `SshMachine` officially requires Bash as the remote default shell, so I'll close this for now. If someone is interested in supporting another shell, it is non-trivial to get some shells to redirect stderr. Fish would be easy.

**Closed by henryiii** 2015-09-18 14:20 UTC
Labels: bug
