### ISSUE TITLE
LocalMachine is not parallel-safe (threadsafe)

### ISSUE THREAD

**Issue by gotgenes** [tomerfiliba/plumbum#169] opened 2015-01-07 22:49 UTC
After following up on #168, I saw that `local` is an instance of `plumbum.machines.local.LocalMachine`. As [stated in the docstring, however, `LocalMachine` was designed to be a singleton](https://github.com/tomerfiliba/plumbum/blob/9cfee6125c2d541ec423e1af8976da02fcc78220/plumbum/machines/local.py#L109). Because new instances of `LocalMachine` would just use the same class attributes for `cwd`, `env`, `python` and the like, it seems that this class is inherently not parallel-safe.

Moving these attributes from class attributes to instance attributes would allow independent contexts of `LocalMachine`. Further, this gives consistency with the design of [`RemoteMachine`](https://github.com/tomerfiliba/plumbum/blob/9cfee6125c2d541ec423e1af8976da02fcc78220/plumbum/machines/remote.py#L136). Is there any negative side-effect from turning these into instance attributes?

**Comment by tomerfiliba** [comment] 2015-01-08 07:35
Environment variables and working directory are singleton "by design" in POSIX/Windows. You can't have "multiple working directories" at once (without using more advance tricks like [openat](http://linux.die.net/man/2/openat)). 

Plumbum attempts to be a popen-replacement, and in doing so it must coexist with "normal system calls", e.g., the user might use `local.cwd.chdir("/tmp/foo")` and then expect the built-in open to work. The same goes for environment variables.

This is exactly why `local.env` and `local.cwd` are context managers -- you can create a stack of working directories or environments, and thus achieve multiplexing. Using your example from #168,

```python
@contextmanager
def virtualenv(virtualenv_dir):
    bindir = local.path(virtualenv_dir) / 'bin'
    old_python = local.python
    local.python = local['python']
    with local.env(PATH = bindir):
        try:
            yield
        finally:
            local.python = old_python
```

now you can nest them, e.g.

```python

with virutalenv("/tmp/venv1"):
    local["pip"]("install", "foobar")
    local.python("-c", "import foobar")  # this should work
    with virtualenv("/tmp/venv2"):
        local.python("-c", "import foobar")  # this should fail
    local.python("-c", "import foobar")  # this should work again
```

I haven't tested the code (tried to simplify your version of it), but it's designed to work like that.

**Comment by tomerfiliba** [comment] 2015-01-30 18:13
closing as "won't fix"

**Closed by tomerfiliba** 2015-01-30 18:13 UTC

**Comment by gotgenes** [comment] 2015-04-07 00:54
I apologize for my delay in getting back on this issue. Here is some code (written for Python 3.4 and newer) which demonstrates the issue at hand, that plumbum `LocalMachine` can not be used safely for concurrent tasks:

```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-

import asyncio

from plumbum.machines import LocalMachine


@asyncio.coroutine
def first_setter():
    local = LocalMachine()
    with local.env(PRIVATE_VAR='before'):
        print("PRIVATE_VAR of first_setter() before sleeping: {}".format(
              local.env['PRIVATE_VAR']))
        yield from asyncio.sleep(1)
        print("PRIVATE_VAR of first_setter() after sleeping: {}".format(
              local.env['PRIVATE_VAR']))


@asyncio.coroutine
def second_setter():
    local = LocalMachine()
    with local.env(PRIVATE_VAR='after'):
        print("PRIVATE_VAR of second_setter(): {}".format(
              local.env['PRIVATE_VAR']))
        yield from asyncio.sleep(3)


loop = asyncio.get_event_loop()
tasks = [asyncio.async(first_setter()), asyncio.async(second_setter())]
loop.run_until_complete(asyncio.wait(tasks))
loop.close()
```

Running the above script gives the following output:

```
PRIVATE_VAR of first_setter() before sleeping: before
PRIVATE_VAR of second_setter(): after
PRIVATE_VAR of first_setter() after sleeping: after
```

Here's what I as a user would expect:

```
PRIVATE_VAR of first_setter() before sleeping: before
PRIVATE_VAR of second_setter(): after
PRIVATE_VAR of first_setter() after sleeping: before
```

The work performed by `first_setter` should be completely isolated from the work in `second_setter`, much like how setting an environment variable in one shell session does not set that variable for a second shell session. As a user, I need a way to safely run multiple tasks concurrently using different contexts (environment variables, cwd, etc.). Letting `LocalMachine()` returns a, independent instance of `LocalMachine`, not the same instance — with its own instances of `LocalEnv`, `LocalWorkdir`, and any other objects that maintain state — would allow plumbum to be used concurrently in a safe manner.

**Comment by edomaur** [comment] 2015-04-07 13:22
Since you are using coroutines, which are run inside the same Posix process, you have the same process environment variables, and the first setter effectively change the PRIVATE_VAR value for every coroutines (or threads, it would be the same problem). In fact, there isn't two PRIVATE_VARs but ONLY ONE as it is defined at the OS process level.

**Comment by gotgenes** [comment] 2015-04-07 13:58
@edomaur This is precisely my point. `LocalMachine` chooses to emulate a single POSIX process, rather than emulate a shell session, with independent environment variables, current working directory, etc. If this is not up for change, then it would be extremely helpful to provide an alternative class to the users that provides isolated execution environments, much how running a command in one shell session makes no impact on a separate shell session.
